deployment_id_label_order:
  - namespace
  - network_name
  - provider
  - environment
  - region
  - stack
  - deployment_id

remote_state_path_label_order:
  - namespace
  - stack
  - provider
  - network_name
  - environment
  - region
#  - deployment_id

dns_order:
  - region
  - provider
  - network_name
  - namespace

id_label_order:
  - namespace
  - stack
  - network_name
  - environment

short_id_label_order:
  - stack
  - environment

name_label_order:
  - namespace
  - stack
  - network_name
  - environment
