version: 2
jobs:
  test:
    docker:
      - image: insightinfrastructure/terragrunt-aws-ci:v0.5.2
    steps:
      - checkout
      - run:
          name: Copy the config and make configs
          command: |
            aws s3 cp s3://ii-ci-1-configs/polkadot.yaml ./config.yaml
            make configs
      - run:
          name: Apply module
          command: |
            ssh-keygen -b 2048 -t rsa -f ./id_rsa -q -N ""
            ./.circleci/test-trigger.sh
      - run:
          name: Destroy on failure
          command: |
            ./cloud-nuke aws --force
          when: on_fail
workflows:
  version: 2
  default:
    jobs:
      - test

