dev:
  api:
    aws:
      api-lb: master
      asg: master
      k8s-cluster: k8s-provider-move
      k8s-config: master
      network: master
    azure:
      api-lb: master
      asg: master
      k8s-cluster: master
      k8s-config: master
      network: master
    gcp:
      api-lb: master
      asg: master
      k8s-cluster: master
      k8s-config: master
      network: master
    do:
      k8s-cluster: master
      k8s-config: master
      network: master

  validator:
    aws:
      node: master
    azure:
      node: master
    gcp:
      node: master
    packet:
      node: master

prod:
  api:
    aws:
      api-lb: master
      asg: master
      k8s-cluster: k8s-provider-move
      k8s-config: master
      network: master
    azure:
      api-lb: master
      asg: master
      k8s-cluster: master
      k8s-config: master
      network: master
    gcp:
      api-lb: master
      asg: master
      k8s-cluster: master
      k8s-config: master
      network: master
    do:
      k8s-cluster: master
      k8s-config: master
      network: master

  validator:
    aws:
      node: master
    azure:
      node: master
    gcp:
      node: master
    packet:
      node: master