---
# Script to set secrets profiles.
#
# - Secrets profiles exist in secrets.yml files at the root
# - They have several fields that have keys that produce a list of profiles.
# - These profiles all have a `name` that is the id of the profile that is looked when applying or destroying.

profiles_intro_:
  type: print
  statement: Configuring SSH and wallet profiles

choice_:
  type: checkbox
  message: Which profiles would you like to set?
  choices:
    - docs: Open docs to explain this
    - ssh: SSH keys
    - wallet: Wallets
#    - dns: DNS settings
#    - cloud: Cloud credentials

docs:
  type: webbrowser
  when: "{{ 'docs' in profiles.choice_ }}"
  url: https://www.notion.so/insightx/Introductory-Tutorials-0416f96a30ee485f9e30c3a75b4910bf

# SSH
ssh_profile_name_:
  type: input
  message: What do you want to call you SSH profile?
  when: "{{ 'ssh' in profiles.choice_ }}"
  
ssh_options_:
  type: select
  message: How would you like to configure your SSH key?
  when: "{{ 'ssh' in profiles.choice_ }}"
  choices:
    - ssh-keygen: Generate new SSH Keys
    - ssh-path: Set path to SSH keys

## SSH Path

ssh_public_key_path_:
  type: input
  message: What path is your public ssh key?
  when:
    - "{{ 'ssh' in profiles.choice_ }}"
    - "{{ profiles.ssh_options_ == 'ssh-path' }}"
  default: "$HOME/.ssh/"

ssh_private_key_path_:
  type: input
  message: What path is your private ssh key?
  when:
    - "{{ 'ssh' in profiles.choice_ }}"
    - "{{ profiles.ssh_options_ == 'ssh-path' }}"
  default: "{{ profiles.ssh_public_key_path_ }}"

ssh_path_add_:
  type: yaml
  when:
    - "{{ 'ssh' in profiles.choice_ }}"
    - "{{ profiles.ssh_options_ == 'ssh-path' }}"
  path: "{{ profiles.secrets_file_ }}"
  in_place: true
  append_items:
    - name: "{{ profiles.ssh_profile_name_ }}"
      public_key_path: "{{ profiles.ssh_public_key_path_ }}"
      private_key_path: "{{ profiles.ssh_private_key_path_ }}"
  append_keys: ssh_profiles

## SSH Generate
ssh_keygen_path_:
  type: input
  message: What path to generate the ssh key?
  when:
    - "{{ 'ssh' in profiles.choice_ }}"
    - "{{ profiles.ssh_options_ == 'ssh-keygen' }}"
  default: "~/.ssh/{{ profiles.ssh_profile_name_ }}"

ssh_keygen_:
  type: command
  when:
    - "{{ 'ssh' in profiles.choice_ }}"
    - "{{ profiles.ssh_options_ == 'ssh-keygen' }}"
  command: |
    ssh-keygen -t rsa -b 4096 -f {{ profiles.ssh_keygen_path_ }}

ssh_keygen_add_:
  type: yaml
  when:
    - "{{ 'ssh' in profiles.choice_ }}"
    - "{{ profiles.ssh_options_ == 'ssh-keygen' }}"
  path: "{{ profiles.secrets_file_ }}"
  in_place: true
  append_items:
    - name: "{{ profiles.ssh_profile_name_ }}"
      public_key_path: "{{ profiles.ssh_keygen_path_ }}.pub"
      private_key_path: "{{ profiles.ssh_keygen_path_ }}"
  append_keys: ssh_profiles

# Wallets
wallet_profile_name_:
  type: input
  message: What do you want to call your wallet profile?
  when: "{{ 'wallet' in profiles.choice_ }}"

wallet_options_:
  type: select
  message: How would you like to configure your wallet profile?
  when: "{{ 'wallet' in profiles.choice_ }}"
  choices:
    - wallet-gen: Generate new wallet
    - wallet-path: Set path to wallet

## Wallet Path
wallet_path_:
  type: input
  message: What path is your wallet?
  when:
    - "{{ 'wallet' in profiles.choice_ }}"
    - "{{ profiles.wallet_options_ == 'wallet-path' }}"
  default: "~/Documents/polkadot/"

wallet_path_add_:
  type: yaml
  when:
    - "{{ 'wallet' in profiles.choice_ }}"
    - "{{ profiles.wallet_options_ == 'wallet-path' }}"
  path: "{{ profiles.secrets_file_ }}"
  in_place: true
  append_items:
    - name: "{{ profiles.wallet_profile_name_ }}"
      bls_key_path: "{{ profiles.wallet_path_ }}"
  append_keys: wallet_profiles

## Wallet Generate
wallet_keygen_path_:
  type: input
  message: What path to generate the wallet key?
  when:
    - "{{ 'wallet' in profiles.choice_ }}"
    - "{{ profiles.wallet_options_ == 'wallet-gen' }}"
  default: "{{cwd}}/wallets/{{ profiles.wallet_profile_name_ }}"

wallet_keygen_:
  type: command
  when:
    - "{{ 'wallet' in profiles.choice_ }}"
    - "{{ profiles.wallet_options_ == 'wallet-gen' }}"
  command: |
    hmy keys generate-bls-key --bls-file-path {{ profiles.wallet_keygen_path_ }}

wallet_keygen_add_:
  type: yaml
  when:
    - "{{ 'wallet' in profiles.choice_ }}"
    - "{{ profiles.wallet_options_ == 'wallet-gen' }}"
  path: "{{ profiles.secrets_file_ }}"
  in_place: true
  append_items:
    - name: "{{ profiles.wallet_profile_name_ }}"
      bls_key_path: "{{ profiles.wallet_keygen_path_ }}"
  append_keys: wallet_profiles

## Cloud Credentials
#cloud_provider_:
#  type: checkbox
#  message: Which cloud provider do you want to set credentials for?
#  choices:
#    - aws
#    - azure
#    - gcp
#    - do
#
### AWS
#cloud_aws_:
#  type: select
#  message: How do you want to set credentials?
#  choices:
#    - Instructions on how to get API keys
#    - Use a profile
#    - Provide API keys
#
#cloud_aws_profile_:
#  type: input
#  message: Which profile do you want to use?
#
#
#cloud_aws_access_key:
#  type: input
#  message: What is your access key id?
#
#
#cloud_write_:
#  type: yaml
#  path: secrets.yml
#  contents: "{{ global }}"
#  in_place: true
#  update:
#
#cloud_azure_:
#  type: checkbox
#  message: How do you want to set credentials?
#  choices:
#    - Provide API keys
#    - Use a profile
